### ISSUE TITLE
Unable to run obfuscate as extraArgs (probably my environment related fault)

### ISSUE THREAD

**Issue by RCSandberg** [hey24sheep/vsts-flutter-tasks#18]
Recap:
When running this first task, it fails.
```
- task: FlutterBuild@0
  inputs:
    projectDirectory: $(projectDirectory)
    buildNumber: ""
    target: 'aab'
    dartDefine: "ENV=dev"
    extraArgs: '--obfuscate --split-debug-info=$(outputsSubDir)/$(debugSymbols)'
```

When running this second task, it succeeds.
```
- task: CmdLine@2
  inputs:
    script: '$(FlutterToolPath)/flutter build appbundle --dart-define=ENV=dev --obfuscate --split-debug-info=$(outputsSubDir)/$(debugSymbols)'
```

The first fails:
`Target file "--obfuscate --split-debug-info=build/app/outputs/debug_symbols" not found.`

The second succeeds:
`✓ Built build/app/outputs/bundle/release/app-release.aab (14.7MB).`

I got your (@hey24sheep) feedback:
_Oh I see, task is right. On pipelines path is relative to the runtime env so you have to pass it from env variables. Otherwise that 'build' folder doesn't exist._

I wrote another reply in previous thread, but moving it here to keep that thread clean.

Excellent that you see :) Unfortunately I don't.. :(

- Both tasks are run in a pipeline.
- Both tasks produce the same command:

`/Users/runner/hostedtoolcache/Flutter/2.0.3-stable/macos/flutter/bin/flutter build appbundle --dart-define=ENV=dev --verbose --obfuscate --split-debug-info=build/app/outputs/debug_symbols`

- Both tasks seems to be executing the command from the same project directory (where pubspec.yaml is).

I enabled system debug and found:
```
##[debug]projectDirectory=/Users/runner/work/1/s
##[debug]Moving to /Users/runner/work/1/s
##[debug]Project's directory : /Users/runner/work/1/s
```

I'm sure you are correct, I just don't know how to go about to fix it... :( Any hints?
I found:
`System and user-defined variables also get injected as environment variables for your platform. When variables are turned into environment variables, variable names become uppercase...`

From: 
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#environment-variables

Tried that, no difference :(

**Comment by hey24sheep** [comment]
I am confused, I don't know what's the difference between the two except the way they work. I had a look [here](https://flutter.dev/docs/deployment/obfuscate). 

Looking at the flutter docs, I could recommend that you could try 
- adding '/' before the path 
- try using it like `--obfuscate --split-debug-info='/build/path/debug_symbols'`

I think either way it could be a standalone argument in build task.

**Comment by RCSandberg** [comment]
I'm pretty confident with how obfuscate works.. at least on local machine :) But for some reason I cannot make it work with the FlutterBuild task :(

Having the slash in front will require the fullpath from root, meaning it that case it won't be relative.

I will try again, because now I'm a bit unsure what I've already tried... But I'm pretty sure I've tried a number of combinations:
```
'build/path/debug_symbols'
'/<fullpath>/build/path/debug_symbols'
'./build/path/debug_symbols'
```
The flutter command should try to create the folder if it is missing. So I would expect a different fault in the stacktrace from flutter.

The missing Target file fault rather sounds like it cannot find the default entry point in creation. Default is lib/main.dart.
If I change the name on my local machine of lib/main.dart to lib/main2.dart
The following happens:
```
flutter build appbundle --obfuscate --split-debug-info=build/app/outputs/debug_symbols
Target file "lib\main.dart" not found.
```
So it's almost like FlutterBuild task for some reason tries to use the wrong entry point

**Comment by RCSandberg** [comment]
Checking the documentation I found this:
`If the --target option is omitted, but a file name is provided on the command line, then that is used instead.`
So for some reason, I suspect that this:
`"--obfuscate --split-debug-info=build/app/outputs/debug_symbols"`

is interpreted as the main entry-point file of the application

**Comment by hey24sheep** [comment]
But then it should fail when used using cmd task, right?

**Comment by RCSandberg** [comment]
Yeah. Very strange :)
But now I saw that FlutterBuild task has a entryPoint input. Just tried that:
```
- task: FlutterBuild@0
  inputs:
    projectDirectory: $(projectDirectory)
    buildNumber: ""
    target: 'aab'
    dartDefine: "ENV=dev"
    entryPoint: 'lib/main.dart'
    extraArgs: '--obfuscate --split-debug-info=$(outputsSubDir)/$(debugSymbols)'
```
Produced this:
`/Users/runner/hostedtoolcache/Flutter/2.0.3-stable/macos/flutter/bin/flutter build appbundle --target=lib/main.dart --dart-define=ENV=dev --obfuscate --split-debug-info=build/app/outputs/debug_symbols`

and this **succeeded**!
```
✓ Built build/app/outputs/bundle/release/app-release.aab (15.3MB).
Finishing: FlutterBuild
```

Very very strange behavior... at least I have a work-around now. It feels more elegant to use a task instead of running Cmd-tasks..

**Comment by hey24sheep** [comment]
Oh yea, we totally missed that. You are using flutter 'dev' flavor so you have to give the entry file. Well, I am glad you found the solution to the problem :)

**Comment by RCSandberg** [comment]
But I'm not running with a --flavor.. just the seprate --dart-define flag. I mean I can change so that it instead is:
`--dart-define=MYVAR=john`

**Comment by hey24sheep** [comment]
Someone with more knowledge on DevOps VM will know something we are missing out and maybe can shed some knowledge here. I will keep this open for now till I add those flags.

**Comment by RCSandberg** [comment]
Okey :) I can give it try later when updates have been made!

Awesomely fast response. Many thanks for the support! Great that you forked the repo!

Cheers!

Edit:
It is low prio to fix since a clear and simple workaround is available.

**Comment by hey24sheep** [comment]
Hey @RCSandberg I have created a new project out this [Azure Flutter Tasks](https://github.com/hey24sheep/azure-flutter-tasks) as the original project is not at all maintained anymore. This will not have any effect on the users of this extension. I will really appreciate if you could star that repo as well. I will close this issue here as I have added extra-args which can fix this issue. If you still want the parameter, please open this issue again on the new repo
