### ISSUE TITLE
Use ipa instead of build for iOS

### ISSUE THREAD

**Issue by marceloavf** [hey24sheep/vsts-flutter-tasks#19]
According to some docs, using `flutter build ipa` instead of `flutter build ios` improves performance.

Build iOS is actually building it twitce, should not be nice to change it?

https://github.com/olmps/memo/pull/98

**Comment by hey24sheep** [comment]
I was thinking of doing it. I have it on my to-do list. I will add another build type so by that way we can support both old flutter builds and new one. It might take some time for me to do as my pc isn't working and I'm working from aN office laptop.

**Comment by hey24sheep** [comment]
#b80c39e Hi @marceloavf I have updated the extension. I have also added a feature of custom urls incase it gets hard to keep up with Flutter updates. Let me know if it helps, I will close this issue afterwards.

**Comment by marceloavf** [comment]
That's awesome, thank you @hey24sheep!
