### ISSUE TITLE
Flutter release URL changed

### ISSUE THREAD

**Issue by aporquez** [hey24sheep/vsts-flutter-tasks#22]
Is there a workaround to the Flutter release URL? 

They changed the format from: https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_2.2.1-stable.zip
To this: https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.2.2-stable.zip

The old URL is using **flutter_infra** while the latest is **flutter_infra_release**.

**Comment by hey24sheep** [comment]
#b80c39e Hi @aporquez I have updated the extension. I have also added a feature of custom urls incase it gets hard to keep up with Flutter updates. Let me know if it helps and fixes it, I will close this issue afterwards.

**Comment by aporquez** [comment]
This is now resolved. Thank you!
