### ISSUE TITLE
Desktop support

### ISSUE THREAD

**Issue by alenros** [hey24sheep/vsts-flutter-tasks#4]
What do you think about adding support for building to desktop?
according to https://flutter.dev/desktop it's as simple as 'flutter build windows'.
If you think it should be added I'd be glad to do it.

**Comment by hey24sheep** [comment]
For now it can be done using command task. I'm unsure that's why I haven't added it yet cuz there are pre-requisites for it for different platforms. Do we install those or do we give a hint? Idk.

**Comment by alenros** [comment]
There are pre-req for the previous steps, too. a macos with xcode and cocoa is required for iOS development.
What was  done to ensure those?

**Comment by hey24sheep** [comment]
Oh yea, you are right, sorry I half brain replied. It is handled by the client. We can implement it by adding desktop to platform list in build task.jsom and adding operating system based on runtime o.s

**Comment by hey24sheep** [comment]
Closing in respect to 'desktop support commit c870ed3'
