### ISSUE TITLE
Make main project out of this

### ISSUE THREAD

**Issue by jakobwgnr** [hey24sheep/vsts-flutter-tasks#9]
Hi!
General Recommendation (as I have also just created a PR to the "wrong" repo):

As this is "just" a fork off the main project search results (e.g. google) don't show this repo. Would recommend to create a new main-repo out of this. You have anyways referenced to aloisdeniel as the first contributor, but otherwise people won't find this repo.

Would also recommend to rename the repo itself as "vsts" is sort of outdated.
Thanks and BR,
Jakob

**Comment by hey24sheep** [comment]
Hi Jakob, 
I had the same idea but that would just be confusing for people and they might still want to use/contribute his original work which is not updated/latest as of now so when they will see his they could check mine from here or from Azure Marketplace so they will know it is same as his but fixed. Also, you can't make repo out of forks unless I either re-create a new repo with new name (I will lose wiki, past commits of his, etc) and stuff or I contact github support. 

I don't want to create a new repo for 2 reasons. First, I want them to know this is just more updated and latest code of his work. Second, so I don't lose his old commits, wiki, refs, etc.

**Comment by jakobwgnr** [comment]
Hi !
understood - Fair reasons. But still 2 extensions / repos (even if fork) is also confusing, at least for me :)
Maybe aloisdeniel would give you owner rights for his repo & so you could merge your work?
BR Jakob

**Comment by BenPoell** [comment]
I'm with Jakob, would be nice if it's somehow possible to take over the ownership to keep that extension alive - it's really worthwhile. I also firstly installed aloisdeniel's unmaintained version because it has 10x more installs on the Marketplace until I figured out it isn't working. 

Br, Benjamin

**Comment by hey24sheep** [comment]
I opened an issue where I pointed the same thing with the hint if he could make me or anyone else a maintainer. But, he never replied on that thread. So, I created this fork out of necessity. I will keep this issue open so other people can give their view or solution. If too many people ask for it maybe I will create a new Repo (w/ new name).

**Comment by aporquez** [comment]
The main project has no updates since October 2020. I would suggest make this a main project rather than a fork.

**Comment by hey24sheep** [comment]
@jakobwgnr @BenPoell @aporquez I have created a new project out this [Azure Flutter Tasks](https://github.com/hey24sheep/azure-flutter-tasks) as the original project is not at all maintained anymore. This will not have any effect on the users of this extension.

**Comment by hey24sheep** [comment]
I would really appreciate if you could star that repo. It will help in people seeing it. Thank you
